---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: cassandra
            image: cassandra:3.11.4
          - name: init
            image: python:alpine
          - name: init2
            image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: analyticsapi
            image: tungstenfabric/contrail-analytics-api:latest
          - name: api
            image: tungstenfabric/contrail-controller-config-api:latest
          - name: collector
            image: tungstenfabric/contrail-analytics-collector:latest
          - name: devicemanager
            image: tungstenfabric/contrail-controller-config-devicemgr:latest
          - name: dnsmasq
            image: tungstenfabric/contrail-external-dnsmasq:latest
          - name: init
            image: python:alpine
          - name: init2
            image: busybox:latest
          - name: redis
            image: redis:4.0.14
          - name: schematransformer
            image: tungstenfabric/contrail-controller-config-schema:latest
          - name: servicemonitor
            image: tungstenfabric/contrail-controller-config-svcmonitor:latest
          - name: queryengine
            image: tungstenfabric/contrail-analytics-query-engine:latest
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: control
            image: tungstenfabric/contrail-controller-control-control:latest
          - name: dns
            image: tungstenfabric/contrail-controller-control-dns:latest
          - name: init
            image: python:alpine
          - name: named
            image: tungstenfabric/contrail-controller-control-named:latest
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: kubemanager
            image: michaelhenkel/contrail-kubernetes-kube-manager:latest
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          zookeeperInstance: zookeeper1
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:alpine
          - name: rabbitmq
            image: rabbitmq:3.7
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermaster
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: nodeinit
            image: tungstenfabric/contrail-node-init:latest
          - name: vrouteragent
            image: tungstenfabric/contrail-vrouter-agent:latest
          - name: vroutercni
            image: michaelhenkel/contrailcni:v0.0.1
          - name: vrouterkernelbuildinit
            image: tungstenfabric/contrail-vrouter-kernel-build-init:latest
          - name: vrouterkernelinit
            image: tungstenfabric/contrail-vrouter-kernel-init:latest
          controlInstance: control1
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouternodes
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.opencontrail.org: vrouter
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: nodeinit
            image: tungstenfabric/contrail-node-init:latest
          - name: vrouteragent
            image: tungstenfabric/contrail-vrouter-agent:latest
          - name: vroutercni
            image: michaelhenkel/contrailcni:v0.0.1
          - name: vrouterkernelbuildinit
            image: tungstenfabric/contrail-vrouter-kernel-build-init:latest
          - name: vrouterkernelinit
            image: tungstenfabric/contrail-vrouter-kernel-init:latest
          controlInstance: control1
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
          - name: init
            image: python:alpine
          - name: redis
            image: redis:4.0.14
          - name: webuijob
            image: tungstenfabric/contrail-controller-webui-job:latest
          - name: webuiweb
            image: tungstenfabric/contrail-controller-webui-web:latest
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:alpine
          - name: zookeeper
            image: zookeeper:3.5.5
