apiVersion: contrail.juniper.net/v1alpha1
kind: ContrailCNI
metadata:
  name: example-contrailcni
  namespace: contrail
spec:
    serviceConfiguration:
      containers:
        - name: vroutercni
          image: tungstenfabric/contrail-kubernetes-cni-init:latest
    commonConfiguration:
      create: true

