bases:
- ../../base/operator

images:
- name: tf-operator
  newTag: latest
  newName: localhost:5000/tf-operator

# To use pre-built operator from dockehub
# images:
# - name: tf-operator
#   newTag: latest
#   newName: tungstenfabric/tf-operator
